services:
  mongo:
    image: mongo:7
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ecommerce-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
