apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    release: monitoring   # 👈 THIS IS CRITICAL
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - mern-app
  endpoints:
    - port: http
      targetPort: 5000
      path: /metrics
      interval: 15s
